# Generated by Django 5.1.2 on 2024-11-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminsidedetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='')),
                ('activities', models.CharField(max_length=100)),
                ('guide_name', models.CharField(max_length=100)),
                ('days', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='usersideinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='')),
                ('pickupdate', models.DateField()),
            ],
        ),
    ]
