# Generated by Django 5.1.2 on 2024-11-22 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersideinfo',
            old_name='name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='usersideinfo',
            old_name='pickupdate',
            new_name='travel_date',
        ),
        migrations.AddField(
            model_name='usersideinfo',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='usersideinfo',
            name='mobile_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersideinfo',
            name='number_of_people',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersideinfo',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bus1.adminsidedetail'),
        ),
    ]
